# Generated by Django 4.1.1 on 2023-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0002_acomment_deleted_at_answer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='stackoverflow.tag'),
        ),
    ]
