# Generated by Django 4.1.1 on 2023-10-17 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0003_alter_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='num_answers',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='num_comments',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
