# Generated by Django 4.1.1 on 2023-10-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0004_remove_answer_num_answers_remove_answer_num_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_comments',
        ),
    ]
