# Generated by Django 4.1.1 on 2023-10-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0005_remove_question_num_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomment',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anscomments', to='stackoverflow.answer'),
        ),
    ]
